version: "3.7"

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - ./.wireguard.env
    volumes:
      - "./config:/config"
      - "/lib/modules:/lib/modules"
    ports:
     - "51820:51820/udp"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped
